language: node_js

python:
  - "2.7"

node_js:
  - '6'
  
before_install:
  - export TZ='Asia/Shenzhen'
  - npm install hexo-cli -g
  - npm install hexo-asset-image --save
  - npm rebuild
  
install:
  - npm install
  
script:
  - root_path=`pwd`
  - ProjectPath=$root_path/source/MDPosts/
  - pwd
  - python 'source/MDPosts/MovePost.py' $ProjectPath
  - hexo clean && hexo g 

after_script:
  - cd ./public
  - git init
  - git config user.name "wlxklyh"  #修改name
  - git config user.email "linyanhou@qq.com"  #修改email
  - git add .
  - git commit -m "travis.ci update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  #only:
  #  - hexo  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/wlxklyh/wlxklyh.github.com.git  #设置GH_REF，注意更改yourname
